GET {{host}}/bookings?size=5&source=MEWS&identifier=1610&businessId=203&startDateTime=2021-09-01T00:00:00.000+0800&endDateTime=2021-10-06T23:59:59.000+0800
Content-Type: application/json
Authorization: {{bearer}}
